#define NANOPRINTF_IMPLEMENTATION
#define NANOPRINTF_USE_FIELD_WIDTH_FORMATTING 1
#define NANOPRINTF_USE_PRECISION_FORMATTING 1
#define NANOPRINTF_USE_SMALL_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_LARGE_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_FLOAT_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_BINARY_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_WRITEBACK_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_PRECISION_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_FIELD_WIDTH_FORMAT_SPECIFIERS 0

/* Satisfy nanoprintf's limits.h dependency without pulling in system headers */
#define CHAR_BIT 8
#define INT_MAX  0x7fffffff
#define INT_MIN  (-INT_MAX - 1)
#define UINT_MAX 0xffffffffu
#define LONG_MAX 0x7fffffffl
#define ULONG_MAX 0xfffffffful
#define LLONG_MAX 0x7fffffffffffffffll
#define ULLONG_MAX 0xffffffffffffffffull

#include "printf.h"